# Site settings
name: AMBITI BLOG
email: fengkai8375@gmail.com
author: FK
url: http://www.fengkai.info/
resume_site: http://www.fengkai.info/me/
github: https://github.com/fengkai8375/
baseurl: ""  #根目录
description: 世界以痛吻我,要我回报以歌.
motto: 世界以痛吻我,要我回报以歌.
banner: 生命注满了爱，就如酒杯斟满了酒。
#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title.html
excerpt_separator:  '<!-- more -->' #文章摘要
paginate: 8
paginate_path: "page:num"
gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
github_username: fengkai8375
highlighter: rouge
markdown: kramdown
FB:
  comments :
    provider : disqus
    disqus :
        short_name : ambiti
